### ISSUE TITLE
Custom Intercom Text patching error

### ISSUE THREAD

**Issue by DinoNuggets2** [louis1706/FacilityManagement#3]
This error is given when modifying the text for the Intercom states
![Screenshot 2023-01-09 185316](https://user-images.githubusercontent.com/91291118/211431232-486aa5e5-199b-4db3-9bfa-f34aaf379a34.png)

EDIT: I believe this error shows up no matter what, even if you have the default configs

**Comment by louis1706** [comment]
it's fix now (if you still getting it contact me on support and send a new report here)
